---
title: "Igor data read in R"
author: "Rui Yang"
date: "September 20, 2016"
output: 
  html_document:
    keep_md: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Explore with tidyverse





```{r}

library(tidyverse)

library(IgorR)

```

## Now I will explore 



```{r}
#tt <- read.ibw("dat16g1x.ibw", Verbose = FALSE, ReturnTimeSeries = TRUE,
#MakeWave = FALSE, HeaderOnly = FALSE)
#plot(tt)
```


```{r}


t16 <- read.ibw("dat16g1x.ibw", Verbose = FALSE, ReturnTimeSeries = FALSE,
MakeWave = TRUE, HeaderOnly = FALSE)

read.ibw("dat15g1x.ibw", Verbose = FALSE, ReturnTimeSeries = FALSE,
MakeWave = TRUE, HeaderOnly = FALSE)

b16 <- read.ibw("dat16field.ibw", Verbose = FALSE, ReturnTimeSeries = FALSE,
MakeWave = TRUE, HeaderOnly = FALSE)

read.ibw("dat15field.ibw", Verbose = FALSE, ReturnTimeSeries = FALSE,
MakeWave = TRUE, HeaderOnly = FALSE)
```


```{r}
plot(dat16field,dat16g1x)
plot(dat15field,dat15g1x)

```

```{r}
#f <- function(x, a, b) {
#     digamma(a*x+b)
#}
#x <- seq(1:100)
#y <- f(seq(1:100), 1,1)
#plot(x,y, geom="line")

#fit <- nls(y~f(x,a,b), data=data.frame(x,y), start=list(a=1, b=1))


```




```{r}
#x = seq(0,1,length=11)
# y =digamma(x+1)
 
# plot(x,y)
 # lm1 = lm(y~digamma(a*x+b),start=list(a=1,b=1))
 # summary(lm1)
 
```




```{r}
#dat16field,dat16g1x
#len <- 24
#x = runif(len)
#y = x^3 + runif(len, min = -0.1, max = 0.1)
#plot(x, y)
#s <- seq(from = 0, to = 1, length = 50)
#lines(s, s^3, lty = 2)

#df <- data.frame(x, y)
#m <- nls(y ~ I(x^power), data = df, start = list(power = 1), trace = T)

```


```{r}

#len <- 24
#x = runif(len)
#y = digamma(x+1) + runif(len, min = -0.1, max = 0.1)
#plot(x, y)

#s <- seq(from = 0, to = 1, length = 50)
#lines(s, digamma(s+1), lty = 2)

#df <- data.frame(x, y)
#m <- nls(y ~ digamma(a*x+b), data = df, start = list(a = 1,b=0.5), trace = T)




#yyy <- predict(m)

#lines(x,yyy)

```




```{r}
q <- 1.6e-19
h <- 6.63e-34
len <- 24
x =  dat16field
#tt=wlcorr(ff.y, 3.3877, 3560, 1, 1, 30, 0, 1)
lin <- 0
  ro <- 3560
  A <- 1
  Bphi <- 1
  Bi <- 1
  Bstar <- 30
  b0 <- 3.3877
  
y =  (lin*x) + ro - A*ro*ro*(q*q/pi/h*((log(abs(x)/abs(Bphi))+digamma(0.5+1/(abs(x)/abs(Bphi))))-(log(abs(x)/(abs(Bphi)+2*abs(Bi)))+digamma(0.5+1/(abs(x)/(abs(Bphi)+2*abs(Bi)))))-2*(log(abs(x)/(abs(Bphi)+abs(Bstar)))+digamma(0.5+1/(abs(x)/(abs(Bphi)+abs(Bstar))))))) 
plot(x, y,lty=2,col="green")


#s <- seq(from = 0, to = 1, length = 50)
#lines(s, digamma(s+1), lty = 2)

df <- data.frame(x, y)
m2 <- nls(y ~ (lin*x) + ro - A*ro*ro*(q*q/pi/h*((log(abs(x)/abs(Bphi))+digamma(0.5+1/(abs(x)/abs(Bphi))))-(log(abs(x)/(abs(Bphi)+2*abs(Bi)))+digamma(0.5+1/(abs(x)/(abs(Bphi)+2*abs(Bi)))))-2*(log(abs(x)/(abs(Bphi)+abs(Bstar)))+digamma(0.5+1/(abs(x)/(abs(Bphi)+abs(Bstar))))))), data = df, start = list(lin=0.1,ro=3560,A=1.2,Bphi=1.1,Bi=1.1,Bstar=28), trace = T,nls.control(maxiter = 500, tol = 1e-02, minFactor = 1/1024/2,
            printEval = FALSE, warnOnly = FALSE))

yyy <- predict(m2)
lines(x,yyy,type = 'l',col="red")
```


```{r}
q <- 1.6e-19
h <- 6.63e-34
len <- 24
x =  dat16field
#tt=wlcorr(ff.y, 3.3877, 3560, 1, 1, 30, 0, 1)
lin <- 0
  ro <- 3560
  A <- 1
  Bphi <- 1
  Bi <- 1
  Bstar <- 30
  b0 <- 3.3877
  
y =  (lin*(x-b0)) + ro - A*ro*ro*(q*q/pi/h*((log(abs(x-b0)/abs(Bphi))+digamma(0.5+1/(abs(x-b0)/abs(Bphi))))-(log(abs(x-b0)/(abs(Bphi)+2*abs(Bi)))+digamma(0.5+1/(abs(x-b0)/(abs(Bphi)+2*abs(Bi)))))-2*(log(abs(x-b0)/(abs(Bphi)+abs(Bstar)))+digamma(0.5+1/(abs(x-b0)/(abs(Bphi)+abs(Bstar))))))) 
plot(x, y,lty=2,col="green")


#s <- seq(from = 0, to = 1, length = 50)
#lines(s, digamma(s+1), lty = 2)

df <- data.frame(x, y)
m3 <- nls(y ~ (lin*(x-b0)) + ro - A*ro*ro*(q*q/pi/h*((log(abs(x-b0)/abs(Bphi))+digamma(0.5+1/(abs(x-b0)/abs(Bphi))))-(log(abs(x-b0)/(abs(Bphi)+2*abs(Bi)))+digamma(0.5+1/(abs(x-b0)/(abs(Bphi)+2*abs(Bi)))))-2*(log(abs(x-b0)/(abs(Bphi)+abs(Bstar)))+digamma(0.5+1/(abs(x-b0)/(abs(Bphi)+abs(Bstar))))))), data = df, start = list(lin=0.1,ro=3560,A=1.2,Bphi=1.1,Bi=1.1,Bstar=28,b0=3.5), trace = T,nls.control(maxiter = 500, tol = 1e-01, minFactor = 1/1024/2,
            printEval = FALSE, warnOnly = FALSE))

yyy2 <- predict(m3)
lines(x,yyy2,type = 'l',col="red")
```






```{r}
q <- 1.6e-19
h <- 6.63e-34
len <- 24
x =  dat16field
#tt=wlcorr(ff.y, 3.3877, 3560, 1, 1, 30, 0, 1)
lin <- 0
  ro <- 3560
  A <- 1
  Bphi <- 1
  Bi <- 1
  Bstar <- 30
  b0 <- 3.3877
  
y = dat16g1x/1000/10e-9 
plot(x, y,lty=2,col="blue")


#s <- seq(from = 0, to = 1, length = 50)
#lines(s, digamma(s+1), lty = 2)

df <- data.frame(x, y)
m4 <- nls(y ~ (lin*(x-b0)) + ro - A*ro*ro*(q*q/pi/h*((log(abs(x-b0)/abs(Bphi))+digamma(0.5+1/(abs(x-b0)/abs(Bphi))))-(log(abs(x-b0)/(abs(Bphi)+2*abs(Bi)))+digamma(0.5+1/(abs(x-b0)/(abs(Bphi)+2*abs(Bi)))))-2*(log(abs(x-b0)/(abs(Bphi)+abs(Bstar)))+digamma(0.5+1/(abs(x-b0)/(abs(Bphi)+abs(Bstar))))))), data = df, start = list(lin=0.0,ro=3560,A=1.2,Bphi=1.1,Bi=1.1,Bstar=28,b0=4), trace = T,nls.control(maxiter = 500, tol = 1e-01, minFactor = 1/1024/2,
            printEval = FALSE, warnOnly = FALSE))

yyy3 <- predict(m4)
lines(x,yyy3,type = 'l',col="red")
```
